# Generated by Django 4.2.1 on 2023-07-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
