# Generated by Django 4.2.1 on 2023-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
